<#
.SYNOPSIS
    Writes docs\TROUBLESHOOTING.md: every error code with its explanation and fix (German, with English titles).
.DESCRIPTION
    Generated from src\Resources\errors.json and the language files, so the page always matches the program.
    Run it after changing error codes or their texts; a unit test checks that the page is up to date.
#>
param(
    [string]$Root = (Split-Path -Parent $PSScriptRoot),
    [string]$OutFile = (Join-Path (Split-Path -Parent $PSScriptRoot) 'docs\TROUBLESHOOTING.md')
)

$ErrorActionPreference = 'Stop'
function Read-Json([string]$Path) { [IO.File]::ReadAllText($Path, [Text.Encoding]::UTF8) | ConvertFrom-Json }
function Get-Text([object]$Language, [string]$Key) { ([string]$Language.$Key).Replace("`r", '').Replace("`n", ' ') }

$codes = @((Read-Json (Join-Path $Root 'src\Resources\errors.json')).errors | ForEach-Object { [string]$_.code } | Sort-Object -Unique)
$de = Read-Json (Join-Path $Root 'src\Resources\lang\de.json')
$en = Read-Json (Join-Path $Root 'src\Resources\lang\en.json')
$groups = [ordered]@{
    '1' = 'Komponenten (rclone, WinFsp, PowerShell)'
    '2' = 'Einstellungen und gespeicherte Anmeldungen'
    '3' = 'Anmeldung und Anbieter'
    '4' = 'Laufwerke'
    '5' = 'Netzwerk und Hintergrunddienst'
    '6' = 'Verschlüsselte Tresore'
    '7' = 'Cache'
    '8' = 'Installation und Updates'
    '9' = 'Allgemein'
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Fehlercodes und Lösungen')
$lines.Add('')
$lines.Add('CloudDrives zeigt bei Problemen einen Code wie `CD-3001` mit Erklärung und Lösung an. Hier stehen alle Codes.')
$lines.Add('Die Diagnose im Menü (*Diagnose & Hilfe*) prüft das System automatisch und behebt vieles selbst.')
$lines.Add('')
$lines.Add('*English: every error code with its title in English below the German text.*')
$lines.Add('')
$lines.Add('<!-- Generated by tools/New-TroubleshootingDoc.ps1 from src/Resources - do not edit by hand. -->')
foreach ($group in $groups.Keys) {
    $members = @($codes | Where-Object { $_ -match "^CD-$group\d{3}$" })
    if ($members.Count -eq 0) { continue }
    $lines.Add('')
    $lines.Add("## $($group)xxx - $($groups[$group])")
    foreach ($code in $members) {
        $lines.Add('')
        $lines.Add("### $code - $(Get-Text $de "error.$code.title")")
        $lines.Add('')
        $lines.Add((Get-Text $de "error.$code.fix"))
        $lines.Add('')
        $lines.Add("*English: $(Get-Text $en "error.$code.title"). $(Get-Text $en "error.$code.fix")*")
    }
}
$text = ($lines -join "`r`n") + "`r`n"
[IO.File]::WriteAllText($OutFile, $text, (New-Object Text.UTF8Encoding($false)))
Write-Host "  Written: $OutFile ($($codes.Count) codes)"
